### ISSUE TITLE
buildorder: -1 is broken

### ISSUE THREAD

**Issue by hanzz** [fedora-modularity/libmodulemd#77]
```
from gi import Repository
r = Repository.get_default() # noqa
r.require('Modulemd') # noqa
from gi.repository import Modulemd

data = """
document: modulemd
version: 1
data:
    summary: A test module in all its beautiful beauty.
    description: This module demonstrates how to write simple modulemd files And can be used for testing the build and release pipeline.
    license:
        module: [ MIT ]
    dependencies:
        buildrequires:
            platform: el8
        requires:
            platform: el8
    references:
        community: https://fedoraproject.org/wiki/Modularity
        documentation: https://fedoraproject.org/wiki/Fedora_Packaging_Guidelines_for_Modules
        tracker: https://taiga.fedorainfracloud.org/project/modularity
    profiles:
        default:
            rpms:
                - tangerine
    api:
        rpms:
            - perl-Tangerine
            - tangerine
    components:
        rpms:
            attr:
                rationale: A build dependency of acl
                ref: rhel-8.0
                buildorder: -1
"""

mmd = Modulemd.Module.new_from_string(data)
mmd.upgrade()
print mmd.get_rpm_components().values()[0].get_buildorder()

```

```
$ python mmd.py 
18446744073709551615
```

**Comment by sgallagher** [comment]
Aaargh, okay I made a mistake and I implemented the buildorder field in the `Modulemd.Component` object as an unsigned 64-bit integer, but you are correct: the spec for modulemd explicitly says it should handle negative integers.

Changing this value is technically an ABI break, though I find it hard to believe that anyone has a buildorder greater than `2^63` in use today, so maybe it makes sense to change this without bumping soname.

@contyk I'd like your opinion here. Our choices are basically:

1. Change the modulemd v2 specification to match the libmodulemd implementation (positive integers only)
1. Break libmodulemd ABI without bumping soname, hoping that no one is really using the upper bits of the value today
1. Break libmodulemd ABI and bump the soname, requiring a rebuild of consumers.

**Comment by frenzymadness** [comment]
If I could vote here, I'd vote for point 2.

I really think that build order lower than zero is useful feature especially when you need to build just one component before the rest so you can specify build order just once for that one component and let the rest with the default (zero).

To help you make a decision I wrote a simple script which clones all modules from dist git and prints all build order settings from all branches. The result is that the biggest build order is 300.

The complete result with a count in the first column and build order in the second one is here:

```
    249 3
    162 4
    110 10
     58 5
     50 20
     47 1
     42 100
     41 0
     39 6
     37 2
     21 7
     15 8
     11 30
     10 102
      7 9
      7 12
      6 40
      6 11
      5 50
      3 16
      3 -10
      3 -1
      2 -5
      2 27
      2 22
      2 21
      2 14
      2 13
      2 103
      2 101
      1 99
      1 -8
      1 75
      1 -4
      1 300
      1 25
      1 200
      1 19
      1 15
      1 -15
```

Hope that helps.

**Comment by sgallagher** [comment]
@contyk, @hanzz and I met for dinner last night and discussed this. Our plan is indeed to implement option 2 above (change the API without bumping soname).

**Comment by FrostyX** [comment]
@sgallagher, thank you for fixing this.
I think, that there is still a small bug, because 

    component = Modulemd.ComponentRpm(name="pkg1", rationale="Just because")
    component.set_buildorder(-1)

works fine, but

    Modulemd.ComponentRpm(name="pkg1", rationale="Just because", buildorder=-1)

still fails with 

    *** TypeError: could not convert value for property `buildorder' from int to guint64

**Comment by sgallagher** [comment]
Yep, that looks like a mistake. I’ll get a fix out tomorrow. Thanks for spotting it!

**Comment by sgallagher** [comment]
@FrostyX I've got builds of libmodulemd 1.6.3 that include this fix going in Fedora Koji right now: https://koji.fedoraproject.org/koji/packageinfo?packageID=24950

Please pull down the one for the appropriate platform and confirm that this issue is fixed. I'll get them into a Bodhi update tomorrow if so.
